### ISSUE TITLE
!repos install

### ISSUE THREAD

**Issue by ghost** [CylanceSPEAR/CyBot#4]
"!repos install " command installs into a wrong directory.

assuming the error as a result of the install into ~[errbot]/data/plugins vs ~[errbot]/plugins

repos installed via this method do not function and generate errors 

`
Some plugins are generating errors:
Traceback (most recent call last):
 File "/home/ubuntu/anaconda3/envs/errbot/lib/python3.7/site-packages/errbot/plugin_manager.py", line 240, in _load_plugins_generic
   plugin_classes = plugin_info.load_plugin_classes(base_module_name, baseclass)
 File "/home/ubuntu/anaconda3/envs/errbot/lib/python3.7/site-packages/errbot/plugin_info.py", line 89, in load_plugin_classes
   spec.loader.exec_module(modu1e)
 File "<frozen importlib._bootstrap_external>", line 728, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "/home/ubuntu/errbot/data/plugins/archertech/err-webutils/webutils.py", line 2, in <module>
   from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'.
`
tried with the following repos

*archertech/err-webutils* 
*fookatchu/GoogleCloudVisionParser*

**Comment by TonyLeeVT** [comment]
Thanks, but we don't use !repos install as part of the setup.
